version: "3.8"
services: 
  postgres:
    image: postgres:latest
    restart: always
    environment: 
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    volumes: 
      - postgres:/var/lib/postgresql/data
    ports: 
      - 5432:5432

volumes:
  postgres: